-- =============================================================================
-- Esquema AgroManager para Oracle Database (Autonomous DB / 19c+)
-- Diferencias respecto a la versión MySQL original:
--   * AUTO_INCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
--   * VARCHAR         -> VARCHAR2
--   * TEXT            -> CLOB
--   * TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -> DEFAULT SYSTIMESTAMP
--   * ON UPDATE CURRENT_TIMESTAMP no existe -> se maneja con trigger genérico.
--   * ENGINE=InnoDB / charset se eliminan (Oracle usa AL32UTF8 a nivel de BD).
--   * CREATE TABLE IF NOT EXISTS no existe -> ejecutar sobre un esquema limpio
--     o envolver cada CREATE en un bloque PL/SQL con manejo de excepciones.
--
-- Ejecutar conectado al esquema de la aplicación (p.ej. ADMIN o un user dedicado).
-- =============================================================================

-- =============================================================================
-- Tablas
-- Orden: usuarios → parcelas → trabajadores → campanas → campanas_parcelas → ingresos → egresos
--        → maquinaria → semillas → tipos_plaga → plagas → riego → fertilizantes
--        → campanas_diario → conductores → remisiones → cambios → usos_fertilizante
-- =============================================================================

CREATE TABLE usuarios (
  id            NUMBER(10)        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR2(120)     NOT NULL,
  email         VARCHAR2(160)     NOT NULL,
  password_hash VARCHAR2(255)     NOT NULL,
  rol           VARCHAR2(40)      DEFAULT 'admin'  NOT NULL,
  estado        VARCHAR2(40)      DEFAULT 'Activo' NOT NULL,
  created_at    TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP         NULL,
  CONSTRAINT uq_usuarios_email    UNIQUE (email),
  CONSTRAINT chk_usuarios_rol     CHECK (rol    IN ('admin', 'supervisor', 'operario')),
  CONSTRAINT chk_usuarios_estado  CHECK (estado IN ('Activo', 'Inactivo'))
);

CREATE TABLE parcelas (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(120) NOT NULL,
  hectareas   NUMBER(10,2),
  cultivo     VARCHAR2(80),
  estado      VARCHAR2(40)  DEFAULT 'Activa' NOT NULL,
  inversion   NUMBER(12,2)  DEFAULT 0 NOT NULL,
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP,
  CONSTRAINT fk_parcelas_usuario  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_parcelas_estado  CHECK (estado IN ('Activa', 'Inactiva', 'En preparación'))
);

CREATE TABLE trabajadores (
  id                NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(120) NOT NULL,
  cargo             VARCHAR2(80),
  salario           NUMBER(12,2)  DEFAULT 0 NOT NULL,
  horas_trabajadas  NUMBER(10)    DEFAULT 0 NOT NULL,
  estado            VARCHAR2(40)  DEFAULT 'Activo' NOT NULL,
  usuario_id        NUMBER(10),
  created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  CONSTRAINT fk_trabajadores_usuario  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_trabajadores_estado  CHECK (estado IN ('Activo', 'Inactivo', 'Suspendido'))
);

-- campanas se define antes de ingresos/egresos para que puedan referenciarla.
CREATE TABLE campanas (
  id           NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(160) NOT NULL,
  fecha_inicio DATE          NOT NULL,
  fecha_fin    DATE          NOT NULL,
  hectareas    NUMBER(10,2),
  lotes        NUMBER(10),
  usuario_id   NUMBER(10),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_campanas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
  -- Los totales financieros y de producción se calculan en V_CAMPANAS_RESUMEN.
);

CREATE TABLE campanas_parcelas (
  campana_id  NUMBER(10) NOT NULL,
  parcela_id  NUMBER(10) NOT NULL,
  CONSTRAINT pk_campanas_parcelas PRIMARY KEY (campana_id, parcela_id),
  CONSTRAINT fk_cp_campana FOREIGN KEY (campana_id) REFERENCES campanas(id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id) ON DELETE CASCADE
);

CREATE TABLE ingresos (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto    VARCHAR2(160) NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  fecha       DATE          NOT NULL,
  tipo        VARCHAR2(40)  NOT NULL,
  parcela_id  NUMBER(10),
  campana_id  NUMBER(10),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_ingresos_parcela  FOREIGN KEY (parcela_id)  REFERENCES parcelas(id)  ON DELETE SET NULL,
  CONSTRAINT fk_ingresos_campana  FOREIGN KEY (campana_id)  REFERENCES campanas(id)  ON DELETE SET NULL,
  CONSTRAINT fk_ingresos_usuario  FOREIGN KEY (usuario_id)  REFERENCES usuarios(id)  ON DELETE SET NULL,
  CONSTRAINT chk_ingresos_tipo    CHECK (tipo IN ('Venta', 'Subsidio', 'Préstamo', 'Otro'))
);

CREATE TABLE egresos (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto    VARCHAR2(160) NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  fecha       DATE          NOT NULL,
  tipo        VARCHAR2(40)  NOT NULL,
  categoria   VARCHAR2(80),
  parcela_id  NUMBER(10),
  campana_id  NUMBER(10),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_egresos_parcela      FOREIGN KEY (parcela_id)  REFERENCES parcelas(id)  ON DELETE SET NULL,
  CONSTRAINT fk_egresos_campana      FOREIGN KEY (campana_id)  REFERENCES campanas(id)  ON DELETE SET NULL,
  CONSTRAINT fk_egresos_usuario      FOREIGN KEY (usuario_id)  REFERENCES usuarios(id)  ON DELETE SET NULL,
  CONSTRAINT chk_egresos_tipo        CHECK (tipo      IN ('Insumos', 'Operación', 'Mantenimiento', 'Personal', 'Otro')),
  CONSTRAINT chk_egresos_categoria   CHECK (categoria IN ('Fertilizantes', 'Combustible', 'Maquinaria', 'Nómina', 'Transporte', 'Otro') OR categoria IS NULL)
);

CREATE TABLE maquinaria (
  id                     NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                 VARCHAR2(160) NOT NULL,
  tipo                   VARCHAR2(80)  NOT NULL,
  estado                 VARCHAR2(40)  DEFAULT 'Operativo' NOT NULL,
  ultimo_mantenimiento   DATE,
  proximo_mantenimiento  DATE,
  usuario_id             NUMBER(10),
  created_at             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_maquinaria_usuario  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_maquinaria_estado  CHECK (estado IN ('Operativo', 'En mantenimiento', 'Fuera de servicio'))
);

CREATE TABLE semillas (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        VARCHAR2(160) NOT NULL,
  cantidad    NUMBER(10,2),
  proveedor   VARCHAR2(120),
  costo       NUMBER(12,2)  DEFAULT 0 NOT NULL,
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_semillas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE tipos_plaga (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        VARCHAR2(120) NOT NULL,
  tratamiento VARCHAR2(160),
  CONSTRAINT uq_tipos_plaga_tipo UNIQUE (tipo)
);

CREATE TABLE plagas (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cultivo     VARCHAR2(120),
  tipo_id     NUMBER(10),
  severidad   VARCHAR2(40),
  fecha_detec DATE,
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_plagas_tipo       FOREIGN KEY (tipo_id)    REFERENCES tipos_plaga(id) ON DELETE SET NULL,
  CONSTRAINT fk_plagas_usuario    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)   ON DELETE SET NULL,
  CONSTRAINT chk_plagas_severidad CHECK (severidad IN ('Alta', 'Media', 'Baja'))
);

CREATE TABLE riego (
  id             NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id     NUMBER(10),
  tipo           VARCHAR2(80),
  ultimo_riego   DATE,
  proximo_riego  DATE,
  consumo_agua   NUMBER(10,2),
  usuario_id     NUMBER(10),
  created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_riego_parcela  FOREIGN KEY (parcela_id)  REFERENCES parcelas(id)  ON DELETE SET NULL,
  CONSTRAINT fk_riego_usuario  FOREIGN KEY (usuario_id)  REFERENCES usuarios(id)  ON DELETE SET NULL
);

CREATE TABLE fertilizantes (
  id           NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(160) NOT NULL,
  estado       VARCHAR2(40)  DEFAULT 'Disponible' NOT NULL,
  costo        NUMBER(12,2)  DEFAULT 0 NOT NULL,
  stock_kg     NUMBER(10,2)  DEFAULT 0 NOT NULL,
  stock_minimo NUMBER(10,2)  DEFAULT 0 NOT NULL,
  usuario_id   NUMBER(10),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_fertilizantes_usuario  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_fertilizantes_estado  CHECK (estado IN ('Disponible', 'Agotado', 'Aplicado'))
);

CREATE TABLE campanas_diario (
  id                   NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campana_id           NUMBER(10)   NOT NULL,
  fecha                DATE         NOT NULL,
  hectareas_cortadas   NUMBER(10,2),
  bultos               NUMBER(10),
  notas                VARCHAR2(255),
  usuario_id           NUMBER(10),
  created_at           TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_campanas_diario_campana  FOREIGN KEY (campana_id)  REFERENCES campanas(id)  ON DELETE CASCADE,
  CONSTRAINT fk_campanas_diario_usuario  FOREIGN KEY (usuario_id)  REFERENCES usuarios(id)  ON DELETE SET NULL
);

CREATE TABLE conductores (
  id      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cc      VARCHAR2(40)  NOT NULL,
  nombre  VARCHAR2(160) NOT NULL,
  tel     VARCHAR2(40),
  CONSTRAINT uq_conductores_cc UNIQUE (cc)
);

CREATE TABLE remisiones (
  id                NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campana_id        NUMBER(10)    NOT NULL,
  fecha             DATE          NOT NULL,
  conductor_id      NUMBER(10),
  vehiculo_placa    VARCHAR2(40),
  origen            VARCHAR2(160),
  destino           VARCHAR2(160),
  cantidad          NUMBER(10,2),
  variedad          VARCHAR2(80),
  tel_propietario   VARCHAR2(40),
  valor_flete       NUMBER(12,2),
  enviado_por_id    NUMBER(10),
  firma_conductor   VARCHAR2(160),
  firma_propietario VARCHAR2(160),
  nota              VARCHAR2(255),
  usuario_id        NUMBER(10),
  created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_remisiones_campana    FOREIGN KEY (campana_id)    REFERENCES campanas(id)    ON DELETE CASCADE,
  CONSTRAINT fk_remisiones_conductor  FOREIGN KEY (conductor_id)  REFERENCES conductores(id) ON DELETE SET NULL,
  CONSTRAINT fk_remisiones_enviado    FOREIGN KEY (enviado_por_id) REFERENCES usuarios(id)   ON DELETE SET NULL,
  CONSTRAINT fk_remisiones_usuario    FOREIGN KEY (usuario_id)    REFERENCES usuarios(id)    ON DELETE SET NULL
);

CREATE TABLE cambios (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo      VARCHAR2(160) NOT NULL,
  descripcion CLOB          NOT NULL,
  tipo        VARCHAR2(40)  DEFAULT 'novedad' NOT NULL,
  creado_por  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_cambios_usuario  FOREIGN KEY (creado_por) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_cambios_tipo    CHECK (tipo IN ('novedad', 'alerta', 'mejora', 'corrección'))
);

CREATE TABLE usos_fertilizante (
  id               NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fertilizante_id  NUMBER(10)   NOT NULL,
  parcela_id       NUMBER(10),
  cantidad_kg      NUMBER(10,2) NOT NULL,
  fecha_uso        DATE         DEFAULT SYSDATE NOT NULL,
  notas            VARCHAR2(255),
  usuario_id       NUMBER(10),
  created_at       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_usos_fertilizante  FOREIGN KEY (fertilizante_id) REFERENCES fertilizantes(id) ON DELETE CASCADE,
  CONSTRAINT fk_usos_parcela       FOREIGN KEY (parcela_id)      REFERENCES parcelas(id)      ON DELETE SET NULL,
  CONSTRAINT fk_usos_usuario       FOREIGN KEY (usuario_id)      REFERENCES usuarios(id)      ON DELETE SET NULL,
  CONSTRAINT chk_usos_cantidad     CHECK (cantidad_kg > 0)
);

-- =============================================================================
-- Triggers para mantener updated_at (Oracle no tiene ON UPDATE CURRENT_TIMESTAMP)
-- =============================================================================

CREATE OR REPLACE TRIGGER trg_usuarios_upd
BEFORE UPDATE ON usuarios
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_parcelas_upd
BEFORE UPDATE ON parcelas
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_trabajadores_upd
BEFORE UPDATE ON trabajadores
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Descuenta stock automáticamente al registrar un uso de fertilizante.
-- Lanza error si el stock disponible es insuficiente.
CREATE OR REPLACE TRIGGER trg_descontar_stock_fertilizante
BEFORE INSERT ON usos_fertilizante
FOR EACH ROW
DECLARE
  v_stock   NUMBER(10,2);
  v_nombre  VARCHAR2(160);
BEGIN
  SELECT stock_kg, nombre
    INTO v_stock, v_nombre
    FROM fertilizantes
   WHERE id = :NEW.fertilizante_id;

  IF v_stock < :NEW.cantidad_kg THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Stock insuficiente para "' || v_nombre || '". ' ||
      'Disponible: ' || v_stock || ' kg, requerido: ' || :NEW.cantidad_kg || ' kg.');
  END IF;

  UPDATE fertilizantes
     SET stock_kg = stock_kg - :NEW.cantidad_kg
   WHERE id = :NEW.fertilizante_id;
END;
/

-- Genera una alerta en cambios cuando se registra una plaga con severidad Alta.
CREATE OR REPLACE TRIGGER trg_alerta_plaga_alta
AFTER INSERT ON plagas
FOR EACH ROW
DECLARE
  v_tipo        VARCHAR2(120);
  v_tratamiento VARCHAR2(160);
BEGIN
  IF UPPER(:NEW.severidad) = 'ALTA' THEN
    BEGIN
      SELECT tipo, tratamiento INTO v_tipo, v_tratamiento
        FROM tipos_plaga WHERE id = :NEW.tipo_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      v_tipo        := 'desconocida';
      v_tratamiento := NULL;
    END;

    INSERT INTO cambios (titulo, descripcion, tipo, creado_por)
    VALUES (
      'Alerta: Plaga de alta severidad detectada',
      'Plaga tipo "' || NVL(v_tipo, 'desconocida') || '" en cultivo ' ||
      NVL(:NEW.cultivo, '—') || '. Tratamiento sugerido: ' ||
      NVL(v_tratamiento, 'No especificado') || '. Fecha detección: ' ||
      TO_CHAR(NVL(:NEW.fecha_detec, SYSDATE), 'DD/MM/YYYY'),
      'alerta',
      :NEW.usuario_id
    );
  END IF;
END;
/

-- =============================================================================
-- Índices (búsquedas multi-tenant por usuario_id y FKs de nueva generación)
-- =============================================================================

CREATE INDEX idx_parcelas_usuario       ON parcelas(usuario_id);
CREATE INDEX idx_trabajadores_usuario   ON trabajadores(usuario_id);
CREATE INDEX idx_ingresos_usuario       ON ingresos(usuario_id, fecha);
CREATE INDEX idx_ingresos_campana       ON ingresos(campana_id);
CREATE INDEX idx_egresos_usuario        ON egresos(usuario_id, fecha);
CREATE INDEX idx_egresos_parcela        ON egresos(parcela_id);
CREATE INDEX idx_egresos_campana        ON egresos(campana_id);
CREATE INDEX idx_maquinaria_usuario     ON maquinaria(usuario_id);
CREATE INDEX idx_semillas_usuario       ON semillas(usuario_id);
CREATE INDEX idx_plagas_usuario         ON plagas(usuario_id, fecha_detec);
CREATE INDEX idx_riego_usuario          ON riego(usuario_id);
CREATE INDEX idx_fertilizantes_usuario  ON fertilizantes(usuario_id);
CREATE INDEX idx_campanas_usuario       ON campanas(usuario_id, fecha_inicio);
CREATE INDEX idx_campanas_diario_camp   ON campanas_diario(campana_id, fecha);
CREATE INDEX idx_remisiones_camp        ON remisiones(campana_id, fecha);
CREATE INDEX idx_usos_fertilizante      ON usos_fertilizante(fertilizante_id, fecha_uso);
CREATE INDEX idx_cambios_created        ON cambios(created_at);
CREATE INDEX idx_remisiones_conductor   ON remisiones(conductor_id);
CREATE INDEX idx_plagas_tipo_id         ON plagas(tipo_id);
CREATE INDEX idx_campanas_parcelas_p    ON campanas_parcelas(parcela_id);
CREATE INDEX idx_remisiones_enviado     ON remisiones(enviado_por_id);

-- =============================================================================
-- Tipos PL/SQL (Collections para sp_aplicar_fertilizantes)
-- =============================================================================

CREATE OR REPLACE TYPE t_uso_fert AS OBJECT (
  fertilizante_id NUMBER,
  cantidad_kg     NUMBER
);
/

CREATE OR REPLACE TYPE t_lista_usos AS TABLE OF t_uso_fert;
/

-- =============================================================================
-- Vistas
-- =============================================================================

-- Resumen general del sistema por usuario (dashboard).
CREATE OR REPLACE VIEW V_DASHBOARD AS
SELECT
  u.id     AS usuario_id,
  u.nombre AS usuario_nombre,
  (SELECT COUNT(*)            FROM parcelas     WHERE usuario_id = u.id AND estado  = 'Activa')  AS parcelas_activas,
  (SELECT COUNT(*)            FROM trabajadores WHERE usuario_id = u.id AND estado  = 'Activo')  AS trabajadores_activos,
  (SELECT NVL(SUM(monto), 0) FROM ingresos     WHERE usuario_id = u.id
     AND TRUNC(fecha, 'MM') = TRUNC(SYSDATE, 'MM'))                                              AS ingresos_mes,
  (SELECT NVL(SUM(monto), 0) FROM egresos      WHERE usuario_id = u.id
     AND TRUNC(fecha, 'MM') = TRUNC(SYSDATE, 'MM'))                                              AS egresos_mes,
  (SELECT COUNT(*)            FROM maquinaria  WHERE usuario_id = u.id)                          AS total_maquinaria,
  (SELECT COUNT(*)            FROM campanas    WHERE usuario_id = u.id
     AND SYSDATE BETWEEN fecha_inicio AND fecha_fin)                                             AS campanas_activas
FROM usuarios u;

-- Ingresos y egresos agrupados por mes para reportes financieros.
CREATE OR REPLACE VIEW V_RESUMEN_FINANCIERO AS
SELECT usuario_id, TRUNC(fecha, 'MM') AS mes, 'Ingreso' AS tipo, SUM(monto) AS total
  FROM ingresos
 GROUP BY usuario_id, TRUNC(fecha, 'MM')
UNION ALL
SELECT usuario_id, TRUNC(fecha, 'MM') AS mes, 'Egreso'  AS tipo, SUM(monto) AS total
  FROM egresos
 GROUP BY usuario_id, TRUNC(fecha, 'MM');

-- Fertilizantes con stock igual o por debajo del mínimo configurado.
CREATE OR REPLACE VIEW V_STOCK_BAJO AS
SELECT
  f.id,
  f.nombre,
  f.stock_kg,
  f.stock_minimo,
  f.stock_kg - f.stock_minimo AS diferencia_kg,
  f.usuario_id
FROM fertilizantes f
WHERE f.stock_minimo > 0
  AND f.stock_kg <= f.stock_minimo;

-- Totales de campaña calculados a partir de ingresos, egresos y diario de cosecha.
-- Reemplaza las columnas derivadas que antes estaban en la tabla campanas.
CREATE OR REPLACE VIEW V_CAMPANAS_RESUMEN AS
SELECT
  c.id          AS campana_id,
  c.nombre,
  c.fecha_inicio,
  c.fecha_fin,
  c.hectareas,
  c.lotes,
  c.usuario_id,
  NVL((SELECT SUM(monto) FROM ingresos WHERE campana_id = c.id), 0)              AS ingreso_total,
  NVL((SELECT SUM(monto) FROM egresos  WHERE campana_id = c.id), 0)              AS egresos_total,
  NVL((SELECT SUM(bultos)            FROM campanas_diario WHERE campana_id = c.id), 0) AS produccion_total,
  NVL((SELECT SUM(hectareas_cortadas) FROM campanas_diario WHERE campana_id = c.id), 0) AS hectareas_cosechadas,
  CASE
    WHEN NVL((SELECT SUM(hectareas_cortadas) FROM campanas_diario WHERE campana_id = c.id), 0) > 0
    THEN ROUND(
           NVL((SELECT SUM(bultos) FROM campanas_diario WHERE campana_id = c.id), 0) /
           (SELECT SUM(hectareas_cortadas) FROM campanas_diario WHERE campana_id = c.id),
           2)
    ELSE 0
  END AS rendimiento_ha
FROM campanas c;

-- =============================================================================
-- Procedimiento almacenado con colección
-- Aplica una lista de fertilizantes a una parcela en una sola llamada.
-- El trigger trg_descontar_stock_fertilizante se dispara por cada ítem.
-- =============================================================================

CREATE OR REPLACE PROCEDURE sp_aplicar_fertilizantes (
  p_lista      IN t_lista_usos,
  p_parcela_id IN NUMBER,
  p_usuario_id IN NUMBER,
  p_fecha      IN DATE DEFAULT SYSDATE
) AS
BEGIN
  IF p_lista IS NULL OR p_lista.COUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'La lista de fertilizantes no puede estar vacía.');
  END IF;

  FOR i IN 1 .. p_lista.COUNT LOOP
    IF p_lista(i).cantidad_kg <= 0 THEN
      RAISE_APPLICATION_ERROR(-20003,
        'La cantidad debe ser mayor a 0 (ítem ' || i || ').');
    END IF;

    INSERT INTO usos_fertilizante (fertilizante_id, parcela_id, cantidad_kg, fecha_uso, usuario_id)
    VALUES (p_lista(i).fertilizante_id, p_parcela_id, p_lista(i).cantidad_kg, p_fecha, p_usuario_id);
  END LOOP;

  COMMIT;
END sp_aplicar_fertilizantes;
/

-- =============================================================================
-- Datos de ejemplo (opcional)
-- Ajusta usuario_id al id real del owner que crees con `npm run db:seed-owner`.
-- =============================================================================

-- INSERT INTO parcelas (nombre, hectareas, cultivo, estado, inversion, usuario_id) VALUES ('Parcela Norte A', 12.5, 'Maíz', 'Activa', 25000, 1);
-- INSERT INTO parcelas (nombre, hectareas, cultivo, estado, inversion, usuario_id) VALUES ('Parcela Sur B', 8.3, 'Soja', 'En preparación', 18000, 1);
-- INSERT INTO trabajadores (nombre, cargo, salario, horas_trabajadas, estado, usuario_id) VALUES ('Juan Pérez', 'Operario', 2500, 160, 'Activo', 1);
-- COMMIT;
