-- =============================================================================
-- AgroManager — Esquema Oracle v2.0
-- Normalización completa: catálogos, nuevas entidades, relaciones limpias
-- =============================================================================

-- ─── SECCIÓN 1: Catálogos (sin dependencias externas) ────────────────────────

CREATE TABLE roles (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(80)  NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_roles_nombre UNIQUE (nombre)
);

-- Estados generales: usuarios, trabajadores, parcelas, siembras
-- Filtrar por contexto ('usuario', 'trabajador', 'parcela', 'siembra')
CREATE TABLE estados (
  id       NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre   VARCHAR2(80) NOT NULL,
  contexto VARCHAR2(80) NOT NULL,
  CONSTRAINT uq_estados UNIQUE (nombre, contexto)
);

CREATE TABLE cargos (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(120) NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_cargos_nombre UNIQUE (nombre)
);

CREATE TABLE tipos_ingreso (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(80)  NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_tipos_ingreso UNIQUE (nombre)
);

CREATE TABLE tipos_riego (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(80)  NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_tipos_riego UNIQUE (nombre)
);

-- Reemplaza "tipo de cultivo": maíz, soja, arroz, etc.
CREATE TABLE tipos_semilla (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(120) NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_tipos_semilla UNIQUE (nombre)
);

CREATE TABLE tipos_maquinaria (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(120) NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_tipos_maquinaria UNIQUE (nombre)
);

CREATE TABLE estados_maquinaria (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(80)  NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT uq_estados_maq UNIQUE (nombre)
);

-- Origen y destino de remisiones (reemplaza VARCHAR2 libre)
CREATE TABLE ubicaciones (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(160) NOT NULL,
  tipo        VARCHAR2(40)  DEFAULT 'Otro' NOT NULL,
  descripcion VARCHAR2(255),
  CONSTRAINT chk_ubicaciones_tipo CHECK (tipo IN ('Finca', 'Planta', 'Bodega', 'Puerto', 'Otro'))
);

-- ─── SECCIÓN 2: Personas ──────────────────────────────────────────────────────

CREATE TABLE personas (
  id     NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(160) NOT NULL,
  cc     VARCHAR2(40),
  tel    VARCHAR2(40),
  tipo   VARCHAR2(40)  DEFAULT 'Otro' NOT NULL,
  CONSTRAINT uq_personas_cc    UNIQUE (cc),
  CONSTRAINT chk_personas_tipo CHECK (tipo IN ('Conductor', 'Propietario', 'Otro'))
);

-- ─── SECCIÓN 3: Usuarios (multi-tenant root) ──────────────────────────────────

CREATE TABLE usuarios (
  id            NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR2(120) NOT NULL,
  email         VARCHAR2(160) NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  rol_id        NUMBER(10),
  estado_id     NUMBER(10),
  created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP,
  CONSTRAINT uq_usuarios_email  UNIQUE (email),
  CONSTRAINT fk_usuarios_rol    FOREIGN KEY (rol_id)    REFERENCES roles(id)   ON DELETE SET NULL,
  CONSTRAINT fk_usuarios_estado FOREIGN KEY (estado_id) REFERENCES estados(id) ON DELETE SET NULL
);

CREATE TABLE proveedores (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(160) NOT NULL,
  contacto    VARCHAR2(120),
  tel         VARCHAR2(40),
  email       VARCHAR2(160),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_proveedores_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- ─── SECCIÓN 4: Parcelas y trabajadores ──────────────────────────────────────

CREATE TABLE parcelas (
  id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          VARCHAR2(120) NOT NULL,
  hectareas       NUMBER(10,2),
  tipo_semilla_id NUMBER(10),
  estado_id       NUMBER(10),
  usuario_id      NUMBER(10),
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  CONSTRAINT fk_parcelas_semilla FOREIGN KEY (tipo_semilla_id) REFERENCES tipos_semilla(id) ON DELETE SET NULL,
  CONSTRAINT fk_parcelas_estado  FOREIGN KEY (estado_id)       REFERENCES estados(id)       ON DELETE SET NULL,
  CONSTRAINT fk_parcelas_usuario FOREIGN KEY (usuario_id)      REFERENCES usuarios(id)      ON DELETE SET NULL
);

CREATE TABLE trabajadores (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(120) NOT NULL,
  cargo_id    NUMBER(10),
  salario     NUMBER(12,2)  DEFAULT 0 NOT NULL,
  estado_id   NUMBER(10),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP,
  CONSTRAINT fk_trabajadores_cargo   FOREIGN KEY (cargo_id)   REFERENCES cargos(id)   ON DELETE SET NULL,
  CONSTRAINT fk_trabajadores_estado  FOREIGN KEY (estado_id)  REFERENCES estados(id)  ON DELETE SET NULL,
  CONSTRAINT fk_trabajadores_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- Reemplaza trabajadores.horas_trabajadas (campo acumulado sin historial)
CREATE TABLE horas_laboradas (
  id            NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trabajador_id NUMBER(10)    NOT NULL,
  fecha         DATE          NOT NULL,
  horas         NUMBER(5,2)   NOT NULL,
  descripcion   VARCHAR2(255),
  usuario_id    NUMBER(10),
  created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_horas_trabajador FOREIGN KEY (trabajador_id) REFERENCES trabajadores(id) ON DELETE CASCADE,
  CONSTRAINT fk_horas_usuario    FOREIGN KEY (usuario_id)    REFERENCES usuarios(id)     ON DELETE SET NULL,
  CONSTRAINT chk_horas_rango     CHECK (horas > 0 AND horas <= 24)
);

-- ─── SECCIÓN 5: Campañas ─────────────────────────────────────────────────────

CREATE TABLE campanas (
  id           NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(160) NOT NULL,
  fecha_inicio DATE          NOT NULL,
  fecha_fin    DATE          NOT NULL,
  hectareas    NUMBER(10,2),
  lotes        NUMBER(10),
  usuario_id   NUMBER(10),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_campanas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE campanas_parcelas (
  campana_id NUMBER(10) NOT NULL,
  parcela_id NUMBER(10) NOT NULL,
  CONSTRAINT pk_campanas_parcelas PRIMARY KEY (campana_id, parcela_id),
  CONSTRAINT fk_cp_campana FOREIGN KEY (campana_id) REFERENCES campanas(id)  ON DELETE CASCADE,
  CONSTRAINT fk_cp_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id)  ON DELETE CASCADE
);

CREATE TABLE campanas_diario (
  id                 NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campana_id         NUMBER(10)   NOT NULL,
  fecha              DATE         NOT NULL,
  hectareas_cortadas NUMBER(10,2),
  bultos             NUMBER(10),
  notas              VARCHAR2(255),
  usuario_id         NUMBER(10),
  created_at         TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_cd_campana FOREIGN KEY (campana_id) REFERENCES campanas(id) ON DELETE CASCADE,
  CONSTRAINT fk_cd_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- ─── SECCIÓN 6: Finanzas ─────────────────────────────────────────────────────

CREATE TABLE ingresos (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto    VARCHAR2(160) NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  fecha       DATE          NOT NULL,
  tipo_id     NUMBER(10),
  parcela_id  NUMBER(10),
  campana_id  NUMBER(10),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_ingresos_tipo    FOREIGN KEY (tipo_id)    REFERENCES tipos_ingreso(id) ON DELETE SET NULL,
  CONSTRAINT fk_ingresos_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id)     ON DELETE SET NULL,
  CONSTRAINT fk_ingresos_campana FOREIGN KEY (campana_id) REFERENCES campanas(id)     ON DELETE SET NULL,
  CONSTRAINT fk_ingresos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)     ON DELETE SET NULL,
  CONSTRAINT chk_ingresos_monto  CHECK (monto > 0)
);

-- categoria eliminada según especificación
CREATE TABLE egresos (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto    VARCHAR2(160) NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  fecha       DATE          NOT NULL,
  tipo        VARCHAR2(40)  NOT NULL,
  parcela_id  NUMBER(10),
  campana_id  NUMBER(10),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_egresos_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id) ON DELETE SET NULL,
  CONSTRAINT fk_egresos_campana FOREIGN KEY (campana_id) REFERENCES campanas(id) ON DELETE SET NULL,
  CONSTRAINT fk_egresos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_egresos_tipo   CHECK (tipo IN ('Insumos', 'Operación', 'Mantenimiento', 'Personal', 'Otro')),
  CONSTRAINT chk_egresos_monto  CHECK (monto > 0)
);

-- ─── SECCIÓN 7: Maquinaria ───────────────────────────────────────────────────

CREATE TABLE maquinaria (
  id                    NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                VARCHAR2(160) NOT NULL,
  tipo_id               NUMBER(10),
  estado_id             NUMBER(10),
  ultimo_mantenimiento  DATE,
  proximo_mantenimiento DATE,
  usuario_id            NUMBER(10),
  created_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_maquinaria_tipo    FOREIGN KEY (tipo_id)    REFERENCES tipos_maquinaria(id)   ON DELETE SET NULL,
  CONSTRAINT fk_maquinaria_estado  FOREIGN KEY (estado_id)  REFERENCES estados_maquinaria(id) ON DELETE SET NULL,
  CONSTRAINT fk_maquinaria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)           ON DELETE SET NULL
);

CREATE TABLE trabajadores_maquinaria (
  trabajador_id NUMBER(10) NOT NULL,
  maquinaria_id NUMBER(10) NOT NULL,
  fecha_inicio  DATE       NOT NULL,
  fecha_fin     DATE,
  CONSTRAINT pk_trab_maq  PRIMARY KEY (trabajador_id, maquinaria_id, fecha_inicio),
  CONSTRAINT fk_tm_trab   FOREIGN KEY (trabajador_id) REFERENCES trabajadores(id) ON DELETE CASCADE,
  CONSTRAINT fk_tm_maq    FOREIGN KEY (maquinaria_id) REFERENCES maquinaria(id)   ON DELETE CASCADE,
  CONSTRAINT chk_tm_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

-- ─── SECCIÓN 8: Semillas y siembras ──────────────────────────────────────────

CREATE TABLE semillas (
  id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_semilla_id NUMBER(10),
  cantidad        NUMBER(10,2),
  proveedor_id    NUMBER(10),
  costo           NUMBER(12,2)  DEFAULT 0 NOT NULL,
  parcela_id      NUMBER(10),
  usuario_id      NUMBER(10),
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_semillas_tipo      FOREIGN KEY (tipo_semilla_id) REFERENCES tipos_semilla(id) ON DELETE SET NULL,
  CONSTRAINT fk_semillas_proveedor FOREIGN KEY (proveedor_id)    REFERENCES proveedores(id)   ON DELETE SET NULL,
  CONSTRAINT fk_semillas_parcela   FOREIGN KEY (parcela_id)      REFERENCES parcelas(id)      ON DELETE SET NULL,
  CONSTRAINT fk_semillas_usuario   FOREIGN KEY (usuario_id)      REFERENCES usuarios(id)      ON DELETE SET NULL
);

CREATE TABLE siembras (
  id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id      NUMBER(10)    NOT NULL,
  tipo_semilla_id NUMBER(10),
  proveedor_id    NUMBER(10),
  fecha_siembra   DATE          NOT NULL,
  cantidad_kg     NUMBER(10,2),
  estado_id       NUMBER(10),
  usuario_id      NUMBER(10),
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_siembras_parcela   FOREIGN KEY (parcela_id)      REFERENCES parcelas(id)      ON DELETE CASCADE,
  CONSTRAINT fk_siembras_semilla   FOREIGN KEY (tipo_semilla_id) REFERENCES tipos_semilla(id) ON DELETE SET NULL,
  CONSTRAINT fk_siembras_proveedor FOREIGN KEY (proveedor_id)    REFERENCES proveedores(id)   ON DELETE SET NULL,
  CONSTRAINT fk_siembras_estado    FOREIGN KEY (estado_id)       REFERENCES estados(id)       ON DELETE SET NULL,
  CONSTRAINT fk_siembras_usuario   FOREIGN KEY (usuario_id)      REFERENCES usuarios(id)      ON DELETE SET NULL
);

-- Reemplaza parcelas.inversion (campo plano sin historial)
-- cantidad = volumen de cultivo involucrado (ha, kg, bultos — unidad libre)
CREATE TABLE inversiones (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  siembra_id  NUMBER(10)    NOT NULL,
  fecha       DATE          NOT NULL,
  descripcion VARCHAR2(255) NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  cantidad    NUMBER(10,2),
  usuario_id  NUMBER(10),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_inversiones_siembra FOREIGN KEY (siembra_id) REFERENCES siembras(id)  ON DELETE CASCADE,
  CONSTRAINT fk_inversiones_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)  ON DELETE SET NULL,
  CONSTRAINT chk_inversiones_monto  CHECK (monto > 0)
);

-- ─── SECCIÓN 9: Plagas ───────────────────────────────────────────────────────

CREATE TABLE tipos_plaga (
  id          NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        VARCHAR2(120) NOT NULL,
  tratamiento VARCHAR2(160),
  CONSTRAINT uq_tipos_plaga UNIQUE (tipo)
);

-- cultivo VARCHAR2 → tipo_semilla_id FK (qué semilla/cultivo está afectado)
CREATE TABLE plagas (
  id              NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_semilla_id NUMBER(10),
  tipo_id         NUMBER(10),
  severidad       VARCHAR2(40),
  fecha_detec     DATE,
  usuario_id      NUMBER(10),
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_plagas_semilla    FOREIGN KEY (tipo_semilla_id) REFERENCES tipos_semilla(id) ON DELETE SET NULL,
  CONSTRAINT fk_plagas_tipo       FOREIGN KEY (tipo_id)         REFERENCES tipos_plaga(id)   ON DELETE SET NULL,
  CONSTRAINT fk_plagas_usuario    FOREIGN KEY (usuario_id)      REFERENCES usuarios(id)      ON DELETE SET NULL,
  CONSTRAINT chk_plagas_severidad CHECK (severidad IN ('Alta', 'Media', 'Baja'))
);

-- ─── SECCIÓN 10: Riego y fertilizantes ───────────────────────────────────────

CREATE TABLE riego (
  id            NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parcela_id    NUMBER(10),
  siembra_id    NUMBER(10),
  tipo_id       NUMBER(10),
  ultimo_riego  DATE,
  proximo_riego DATE,
  consumo_agua  NUMBER(10,2),
  usuario_id    NUMBER(10),
  created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_riego_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id)    ON DELETE SET NULL,
  CONSTRAINT fk_riego_siembra FOREIGN KEY (siembra_id) REFERENCES siembras(id)    ON DELETE SET NULL,
  CONSTRAINT fk_riego_tipo    FOREIGN KEY (tipo_id)    REFERENCES tipos_riego(id)  ON DELETE SET NULL,
  CONSTRAINT fk_riego_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)    ON DELETE SET NULL
);

CREATE TABLE fertilizantes (
  id           NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(160) NOT NULL,
  estado       VARCHAR2(40)  DEFAULT 'Disponible' NOT NULL,
  costo        NUMBER(12,2)  DEFAULT 0 NOT NULL,
  stock_kg     NUMBER(10,2)  DEFAULT 0 NOT NULL,
  stock_minimo NUMBER(10,2)  DEFAULT 0 NOT NULL,
  usuario_id   NUMBER(10),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_fertilizantes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT chk_fertilizantes_estado CHECK (estado IN ('Disponible', 'Agotado', 'Aplicado'))
);

-- siembra_id añadido: fertilizante conectado con el cultivo activo
CREATE TABLE usos_fertilizante (
  id              NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fertilizante_id NUMBER(10)   NOT NULL,
  siembra_id      NUMBER(10),
  parcela_id      NUMBER(10),
  cantidad_kg     NUMBER(10,2) NOT NULL,
  fecha_uso       DATE         DEFAULT SYSDATE NOT NULL,
  notas           VARCHAR2(255),
  usuario_id      NUMBER(10),
  created_at      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_usos_fertilizante FOREIGN KEY (fertilizante_id) REFERENCES fertilizantes(id) ON DELETE CASCADE,
  CONSTRAINT fk_usos_siembra      FOREIGN KEY (siembra_id)      REFERENCES siembras(id)      ON DELETE SET NULL,
  CONSTRAINT fk_usos_parcela      FOREIGN KEY (parcela_id)      REFERENCES parcelas(id)      ON DELETE SET NULL,
  CONSTRAINT fk_usos_usuario      FOREIGN KEY (usuario_id)      REFERENCES usuarios(id)      ON DELETE SET NULL,
  CONSTRAINT chk_usos_cantidad    CHECK (cantidad_kg > 0)
);

-- ─── SECCIÓN 11: Conductores y remisiones ────────────────────────────────────

-- Conductores como subtipo de personas
CREATE TABLE conductores (
  id         NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id NUMBER(10)   NOT NULL,
  licencia   VARCHAR2(40),
  created_at TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_conductores_persona FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE,
  CONSTRAINT uq_conductores_persona UNIQUE (persona_id)
);

-- origen/destino VARCHAR2 libre → FK a ubicaciones
CREATE TABLE remisiones (
  id                NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campana_id        NUMBER(10)    NOT NULL,
  fecha             DATE          NOT NULL,
  conductor_id      NUMBER(10),
  vehiculo_placa    VARCHAR2(40),
  origen_id         NUMBER(10),
  destino_id        NUMBER(10),
  cantidad          NUMBER(10,2),
  variedad          VARCHAR2(80),
  tel_propietario   VARCHAR2(40),
  valor_flete       NUMBER(12,2),
  enviado_por_id    NUMBER(10),
  firma_conductor   VARCHAR2(160),
  firma_propietario VARCHAR2(160),
  nota              VARCHAR2(255),
  usuario_id        NUMBER(10),
  created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_rem_campana   FOREIGN KEY (campana_id)     REFERENCES campanas(id)    ON DELETE CASCADE,
  CONSTRAINT fk_rem_conductor FOREIGN KEY (conductor_id)   REFERENCES conductores(id) ON DELETE SET NULL,
  CONSTRAINT fk_rem_origen    FOREIGN KEY (origen_id)      REFERENCES ubicaciones(id) ON DELETE SET NULL,
  CONSTRAINT fk_rem_destino   FOREIGN KEY (destino_id)     REFERENCES ubicaciones(id) ON DELETE SET NULL,
  CONSTRAINT fk_rem_enviado   FOREIGN KEY (enviado_por_id) REFERENCES usuarios(id)    ON DELETE SET NULL,
  CONSTRAINT fk_rem_usuario   FOREIGN KEY (usuario_id)     REFERENCES usuarios(id)    ON DELETE SET NULL
);

-- =============================================================================
-- Triggers
-- =============================================================================

CREATE OR REPLACE TRIGGER trg_usuarios_upd
BEFORE UPDATE ON usuarios FOR EACH ROW
BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_parcelas_upd
BEFORE UPDATE ON parcelas FOR EACH ROW
BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_trabajadores_upd
BEFORE UPDATE ON trabajadores FOR EACH ROW
BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

-- Descuenta stock al registrar uso; lanza error si es insuficiente
CREATE OR REPLACE TRIGGER trg_descontar_stock_fertilizante
BEFORE INSERT ON usos_fertilizante
FOR EACH ROW
DECLARE
  v_stock  NUMBER(10,2);
  v_nombre VARCHAR2(160);
BEGIN
  SELECT stock_kg, nombre INTO v_stock, v_nombre
    FROM fertilizantes WHERE id = :NEW.fertilizante_id;

  IF v_stock < :NEW.cantidad_kg THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Stock insuficiente para "' || v_nombre || '". ' ||
      'Disponible: ' || v_stock || ' kg, requerido: ' || :NEW.cantidad_kg || ' kg.');
  END IF;

  UPDATE fertilizantes
     SET stock_kg = stock_kg - :NEW.cantidad_kg
   WHERE id = :NEW.fertilizante_id;
END;
/

-- Sincroniza estado Disponible/Agotado automáticamente al cambiar stock
CREATE OR REPLACE TRIGGER trg_estado_fertilizante
BEFORE UPDATE OF stock_kg ON fertilizantes
FOR EACH ROW
BEGIN
  IF :NEW.stock_kg <= 0 THEN
    :NEW.estado := 'Agotado';
  ELSIF :NEW.stock_kg > 0 AND :OLD.estado = 'Agotado' THEN
    :NEW.estado := 'Disponible';
  END IF;
END;
/

-- =============================================================================
-- Índices
-- =============================================================================

CREATE INDEX idx_usuarios_rol            ON usuarios(rol_id);
CREATE INDEX idx_usuarios_estado         ON usuarios(estado_id);
CREATE INDEX idx_proveedores_usuario     ON proveedores(usuario_id);
CREATE INDEX idx_parcelas_usuario        ON parcelas(usuario_id);
CREATE INDEX idx_parcelas_semilla        ON parcelas(tipo_semilla_id);
CREATE INDEX idx_trabajadores_usuario    ON trabajadores(usuario_id);
CREATE INDEX idx_trabajadores_cargo      ON trabajadores(cargo_id);
CREATE INDEX idx_horas_trabajador        ON horas_laboradas(trabajador_id, fecha);
CREATE INDEX idx_horas_usuario           ON horas_laboradas(usuario_id);
CREATE INDEX idx_campanas_usuario        ON campanas(usuario_id, fecha_inicio);
CREATE INDEX idx_campanas_parcelas_p     ON campanas_parcelas(parcela_id);
CREATE INDEX idx_campanas_diario_camp    ON campanas_diario(campana_id, fecha);
CREATE INDEX idx_ingresos_usuario        ON ingresos(usuario_id, fecha);
CREATE INDEX idx_ingresos_campana        ON ingresos(campana_id);
CREATE INDEX idx_ingresos_tipo           ON ingresos(tipo_id);
CREATE INDEX idx_egresos_usuario         ON egresos(usuario_id, fecha);
CREATE INDEX idx_egresos_parcela         ON egresos(parcela_id);
CREATE INDEX idx_egresos_campana         ON egresos(campana_id);
CREATE INDEX idx_maquinaria_usuario      ON maquinaria(usuario_id);
CREATE INDEX idx_maquinaria_tipo         ON maquinaria(tipo_id);
CREATE INDEX idx_maquinaria_estado       ON maquinaria(estado_id);
CREATE INDEX idx_trab_maq_maquinaria     ON trabajadores_maquinaria(maquinaria_id);
CREATE INDEX idx_semillas_usuario        ON semillas(usuario_id);
CREATE INDEX idx_semillas_tipo           ON semillas(tipo_semilla_id);
CREATE INDEX idx_semillas_parcela        ON semillas(parcela_id);
CREATE INDEX idx_siembras_parcela        ON siembras(parcela_id, fecha_siembra);
CREATE INDEX idx_siembras_semilla        ON siembras(tipo_semilla_id);
CREATE INDEX idx_siembras_usuario        ON siembras(usuario_id);
CREATE INDEX idx_inversiones_siembra     ON inversiones(siembra_id, fecha);
CREATE INDEX idx_inversiones_usuario     ON inversiones(usuario_id);
CREATE INDEX idx_plagas_usuario          ON plagas(usuario_id, fecha_detec);
CREATE INDEX idx_plagas_tipo_semilla     ON plagas(tipo_semilla_id);
CREATE INDEX idx_plagas_tipo             ON plagas(tipo_id);
CREATE INDEX idx_riego_usuario           ON riego(usuario_id);
CREATE INDEX idx_riego_siembra           ON riego(siembra_id);
CREATE INDEX idx_riego_tipo              ON riego(tipo_id);
CREATE INDEX idx_fertilizantes_usuario   ON fertilizantes(usuario_id);
CREATE INDEX idx_usos_fertilizante       ON usos_fertilizante(fertilizante_id, fecha_uso);
CREATE INDEX idx_usos_siembra            ON usos_fertilizante(siembra_id);
CREATE INDEX idx_conductores_persona     ON conductores(persona_id);
CREATE INDEX idx_remisiones_camp         ON remisiones(campana_id, fecha);
CREATE INDEX idx_remisiones_conductor    ON remisiones(conductor_id);
CREATE INDEX idx_remisiones_origen       ON remisiones(origen_id);
CREATE INDEX idx_remisiones_destino      ON remisiones(destino_id);
CREATE INDEX idx_remisiones_enviado      ON remisiones(enviado_por_id);

-- =============================================================================
-- Tipos PL/SQL (Collections)
-- =============================================================================

CREATE OR REPLACE TYPE t_uso_fert AS OBJECT (
  fertilizante_id NUMBER,
  cantidad_kg     NUMBER
);
/

CREATE OR REPLACE TYPE t_lista_usos AS TABLE OF t_uso_fert;
/

CREATE OR REPLACE TYPE t_hora_lab AS OBJECT (
  fecha       DATE,
  horas       NUMBER,
  descripcion VARCHAR2(255)
);
/

CREATE OR REPLACE TYPE t_lista_horas AS TABLE OF t_hora_lab;
/

-- =============================================================================
-- Vistas
-- =============================================================================

CREATE OR REPLACE VIEW V_DASHBOARD AS
SELECT
  u.id               AS usuario_id,
  u.nombre           AS usuario_nombre,
  r.nombre           AS rol,
  e.nombre           AS estado,
  (SELECT COUNT(*) FROM parcelas p
     JOIN estados ep ON ep.id = p.estado_id AND ep.nombre = 'Activa'
   WHERE p.usuario_id = u.id)                                       AS parcelas_activas,
  (SELECT COUNT(*) FROM trabajadores t
     JOIN estados et ON et.id = t.estado_id AND et.nombre = 'Activo'
   WHERE t.usuario_id = u.id)                                       AS trabajadores_activos,
  (SELECT NVL(SUM(monto), 0) FROM ingresos
   WHERE usuario_id = u.id
     AND TRUNC(fecha, 'MM') = TRUNC(SYSDATE, 'MM'))                 AS ingresos_mes,
  (SELECT NVL(SUM(monto), 0) FROM egresos
   WHERE usuario_id = u.id
     AND TRUNC(fecha, 'MM') = TRUNC(SYSDATE, 'MM'))                 AS egresos_mes,
  (SELECT COUNT(*) FROM maquinaria WHERE usuario_id = u.id)         AS total_maquinaria,
  (SELECT COUNT(*) FROM campanas
   WHERE usuario_id = u.id
     AND SYSDATE BETWEEN fecha_inicio AND fecha_fin)                 AS campanas_activas,
  (SELECT COUNT(*) FROM siembras s
     JOIN estados es ON es.id = s.estado_id AND es.nombre = 'Activa'
   WHERE s.usuario_id = u.id)                                       AS siembras_activas
FROM usuarios u
LEFT JOIN roles   r ON r.id = u.rol_id
LEFT JOIN estados e ON e.id = u.estado_id;

CREATE OR REPLACE VIEW V_RESUMEN_FINANCIERO AS
SELECT usuario_id, TRUNC(fecha, 'MM') AS mes, 'Ingreso' AS tipo, SUM(monto) AS total
  FROM ingresos GROUP BY usuario_id, TRUNC(fecha, 'MM')
UNION ALL
SELECT usuario_id, TRUNC(fecha, 'MM') AS mes, 'Egreso'  AS tipo, SUM(monto) AS total
  FROM egresos  GROUP BY usuario_id, TRUNC(fecha, 'MM');

CREATE OR REPLACE VIEW V_STOCK_BAJO AS
SELECT
  f.id,
  f.nombre,
  f.stock_kg,
  f.stock_minimo,
  f.stock_kg - f.stock_minimo AS diferencia_kg,
  f.usuario_id
FROM fertilizantes f
WHERE f.stock_minimo > 0
  AND f.stock_kg <= f.stock_minimo;

CREATE OR REPLACE VIEW V_CAMPANAS_RESUMEN AS
SELECT
  c.id          AS campana_id,
  c.nombre,
  c.fecha_inicio,
  c.fecha_fin,
  c.hectareas,
  c.lotes,
  c.usuario_id,
  NVL((SELECT SUM(monto)             FROM ingresos       WHERE campana_id = c.id), 0) AS ingreso_total,
  NVL((SELECT SUM(monto)             FROM egresos        WHERE campana_id = c.id), 0) AS egresos_total,
  NVL((SELECT SUM(bultos)            FROM campanas_diario WHERE campana_id = c.id), 0) AS produccion_total,
  NVL((SELECT SUM(hectareas_cortadas) FROM campanas_diario WHERE campana_id = c.id), 0) AS hectareas_cosechadas,
  CASE
    WHEN NVL((SELECT SUM(hectareas_cortadas) FROM campanas_diario WHERE campana_id = c.id), 0) > 0
    THEN ROUND(
           NVL((SELECT SUM(bultos) FROM campanas_diario WHERE campana_id = c.id), 0) /
           (SELECT SUM(hectareas_cortadas) FROM campanas_diario WHERE campana_id = c.id), 2)
    ELSE 0
  END AS rendimiento_ha
FROM campanas c;

-- Total de horas por trabajador (útil para nómina y reportes)
CREATE OR REPLACE VIEW V_TRABAJADORES_HORAS AS
SELECT
  t.id          AS trabajador_id,
  t.nombre      AS trabajador_nombre,
  c.nombre      AS cargo,
  e.nombre      AS estado,
  t.salario,
  t.usuario_id,
  NVL(SUM(h.horas), 0)                                           AS horas_totales,
  NVL(SUM(CASE WHEN TRUNC(h.fecha,'MM') = TRUNC(SYSDATE,'MM')
               THEN h.horas END), 0)                             AS horas_mes_actual,
  COUNT(DISTINCT h.fecha)                                        AS dias_trabajados
FROM trabajadores t
LEFT JOIN cargos        c ON c.id = t.cargo_id
LEFT JOIN estados       e ON e.id = t.estado_id
LEFT JOIN horas_laboradas h ON h.trabajador_id = t.id
GROUP BY t.id, t.nombre, c.nombre, e.nombre, t.salario, t.usuario_id;

-- Siembras con resumen de inversión y uso de fertilizantes
CREATE OR REPLACE VIEW V_SIEMBRAS_RESUMEN AS
SELECT
  s.id              AS siembra_id,
  s.fecha_siembra,
  s.cantidad_kg,
  p.nombre          AS parcela,
  ts.nombre         AS tipo_semilla,
  pr.nombre         AS proveedor,
  e.nombre          AS estado,
  s.usuario_id,
  NVL((SELECT SUM(monto) FROM inversiones     WHERE siembra_id = s.id), 0) AS inversion_total,
  NVL((SELECT SUM(cantidad_kg) FROM usos_fertilizante WHERE siembra_id = s.id), 0) AS fertilizante_kg
FROM siembras s
LEFT JOIN parcelas      p  ON p.id  = s.parcela_id
LEFT JOIN tipos_semilla ts ON ts.id = s.tipo_semilla_id
LEFT JOIN proveedores   pr ON pr.id = s.proveedor_id
LEFT JOIN estados       e  ON e.id  = s.estado_id;

-- Maquinaria con nombres de tipo y estado (evita joins manuales en el backend)
CREATE OR REPLACE VIEW V_MAQUINARIA_DETALLE AS
SELECT
  m.id,
  m.nombre,
  tm.nombre                AS tipo,
  em.nombre                AS estado,
  m.ultimo_mantenimiento,
  m.proximo_mantenimiento,
  m.usuario_id,
  m.created_at,
  (SELECT COUNT(*) FROM trabajadores_maquinaria
   WHERE maquinaria_id = m.id AND fecha_fin IS NULL) AS operadores_activos
FROM maquinaria m
LEFT JOIN tipos_maquinaria   tm ON tm.id = m.tipo_id
LEFT JOIN estados_maquinaria em ON em.id = m.estado_id;

-- =============================================================================
-- Procedimientos almacenados
-- =============================================================================

-- Aplica una lista de fertilizantes a una siembra/parcela en una sola llamada
CREATE OR REPLACE PROCEDURE sp_aplicar_fertilizantes (
  p_lista      IN t_lista_usos,
  p_parcela_id IN NUMBER,
  p_siembra_id IN NUMBER DEFAULT NULL,
  p_usuario_id IN NUMBER,
  p_fecha      IN DATE DEFAULT SYSDATE
) AS
BEGIN
  IF p_lista IS NULL OR p_lista.COUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'La lista de fertilizantes no puede estar vacía.');
  END IF;

  FOR i IN 1 .. p_lista.COUNT LOOP
    IF p_lista(i).cantidad_kg <= 0 THEN
      RAISE_APPLICATION_ERROR(-20003,
        'La cantidad debe ser mayor a 0 (ítem ' || i || ').');
    END IF;

    INSERT INTO usos_fertilizante
      (fertilizante_id, siembra_id, parcela_id, cantidad_kg, fecha_uso, usuario_id)
    VALUES
      (p_lista(i).fertilizante_id, p_siembra_id, p_parcela_id,
       p_lista(i).cantidad_kg, p_fecha, p_usuario_id);
  END LOOP;

  COMMIT;
END sp_aplicar_fertilizantes;
/

-- Registra múltiples jornadas laborales para un trabajador en un lote
CREATE OR REPLACE PROCEDURE sp_registrar_jornadas (
  p_trabajador_id IN NUMBER,
  p_usuario_id    IN NUMBER,
  p_lista         IN t_lista_horas
) AS
BEGIN
  IF p_lista IS NULL OR p_lista.COUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20004, 'La lista de jornadas no puede estar vacía.');
  END IF;

  FOR i IN 1 .. p_lista.COUNT LOOP
    IF p_lista(i).horas <= 0 OR p_lista(i).horas > 24 THEN
      RAISE_APPLICATION_ERROR(-20005,
        'Horas fuera de rango en jornada ' || i || ' (debe ser entre 0 y 24).');
    END IF;

    INSERT INTO horas_laboradas
      (trabajador_id, fecha, horas, descripcion, usuario_id)
    VALUES
      (p_trabajador_id, p_lista(i).fecha, p_lista(i).horas,
       p_lista(i).descripcion, p_usuario_id);
  END LOOP;

  COMMIT;
END sp_registrar_jornadas;
/

-- Devuelve total de horas de un trabajador en un rango de fechas
CREATE OR REPLACE FUNCTION fn_horas_trabajador (
  p_trabajador_id IN NUMBER,
  p_desde         IN DATE DEFAULT TRUNC(SYSDATE, 'MM'),
  p_hasta         IN DATE DEFAULT SYSDATE
) RETURN NUMBER AS
  v_total NUMBER := 0;
BEGIN
  SELECT NVL(SUM(horas), 0)
    INTO v_total
    FROM horas_laboradas
   WHERE trabajador_id = p_trabajador_id
     AND fecha BETWEEN p_desde AND p_hasta;
  RETURN v_total;
END fn_horas_trabajador;
/

-- =============================================================================
-- Datos iniciales de catálogos
-- =============================================================================

INSERT ALL
  INTO roles (nombre, descripcion) VALUES ('admin',      'Acceso total al sistema')
  INTO roles (nombre, descripcion) VALUES ('supervisor', 'Gestión operativa sin configuración')
  INTO roles (nombre, descripcion) VALUES ('operario',   'Registro de actividades de campo')
SELECT 1 FROM dual;

INSERT ALL
  INTO estados (nombre, contexto) VALUES ('Activo',   'usuario')
  INTO estados (nombre, contexto) VALUES ('Inactivo', 'usuario')
  INTO estados (nombre, contexto) VALUES ('Activo',   'trabajador')
  INTO estados (nombre, contexto) VALUES ('Inactivo', 'trabajador')
  INTO estados (nombre, contexto) VALUES ('Suspendido','trabajador')
  INTO estados (nombre, contexto) VALUES ('Activa',         'parcela')
  INTO estados (nombre, contexto) VALUES ('Inactiva',       'parcela')
  INTO estados (nombre, contexto) VALUES ('En preparación', 'parcela')
  INTO estados (nombre, contexto) VALUES ('Activa',    'siembra')
  INTO estados (nombre, contexto) VALUES ('Cosechada', 'siembra')
  INTO estados (nombre, contexto) VALUES ('Perdida',   'siembra')
SELECT 1 FROM dual;

INSERT ALL
  INTO estados_maquinaria (nombre) VALUES ('Operativo')
  INTO estados_maquinaria (nombre) VALUES ('En mantenimiento')
  INTO estados_maquinaria (nombre) VALUES ('Fuera de servicio')
SELECT 1 FROM dual;

INSERT ALL
  INTO tipos_ingreso (nombre) VALUES ('Venta')
  INTO tipos_ingreso (nombre) VALUES ('Subsidio')
  INTO tipos_ingreso (nombre) VALUES ('Préstamo')
  INTO tipos_ingreso (nombre) VALUES ('Otro')
SELECT 1 FROM dual;

INSERT ALL
  INTO tipos_riego (nombre) VALUES ('Goteo')
  INTO tipos_riego (nombre) VALUES ('Aspersión')
  INTO tipos_riego (nombre) VALUES ('Gravedad')
  INTO tipos_riego (nombre) VALUES ('Inundación')
SELECT 1 FROM dual;

COMMIT;

-- =============================================================================
-- Fin del esquema
-- Ejecutar seed-owner.js para crear el primer usuario administrador
-- =============================================================================
